# Section A

**Q1. What's the difference between a Series and a DataFrame? Give one operation that works on both,and one that works only on a DataFrame.**

the difference btw series and datafarms are simple thats the data is stored on which formate is indecating like serice mean is an one diamnstion data thas store only one kind of information,and datafram is an two dimenstional thats is used to store more colums for an example a matrix
for both we use the fuction is mean() to get the average of given data
for only df is df[['name','age']]

**Q2. What does inplace=True do? Why is the pandas team discouraging its use in newer versions? Give
one example where you'd avoid it.**

inplace=True this is an py code thats used to change the original dataset if we perfom some of opreations like cleaning or sliceing thses not removed on the real dataset if we use the inplace=True this on code thats do on orinal datasets

df_age=df(df['age'<30])

df_age.drop(columns=['stats'],inplace=True)

if we run this, the removed are cant be undo

**Q3. Explain the difference between .fillna() and .dropna(). When would a data analyst pick one over the
other? Be specific - give a concrete situation for each.**

fillna() its a functionthats is used to filling an value if the given data set have null or empty thats fiiled withs some randoms thats it is used to maintan the full dataset without loosing information

dropna() is an oppsite like function of fillna() this dropna thats drops or remove the columns or dats rows which is most have the null values and this used to redueses the size of datset is also damges the dataset for loosing of immportant informations

**Q4. What does pd.to_numeric(col, errors='coerce') do that plain pd.to_numeric(col) does NOT? Which
one would you use on real-world messy data, and why?**

plain pd.to_numeric(col) this an function thats is used to check or convert the data  suppose we have fiiled of salares thast are all can be filled some is not fiiled or enter wrong at statring if we use this functionit not convert a single one and at last throwing the error valuerror like massage will be appered at last

plain pd.to_numeric(col,errors='coerce) this also not converts the values but using this on real world data is an good deision becase of if try to convert the data if any known data or unreadable is appeaerd it simliy replace with wi nan

**Q5. Explain .loc vs .iloc with one example each. Then describe a case where df.loc[0] and df.iloc[0]
return different rows.**

.loc is a label based thats selects rows and columns using their names lables for an example name or age liek

.iloc is a integer postion based that is allowed you to chooses the postion of index of thats and based on labels
for an example of data set have index like:2,3,0
and produxts are apple, mongo,barry
if we loaded the data into df the query is

x=df.loc[0]
this will given an output is 0,bannan

y=df.iloc[0]
if we run this thats give an first row of the data is  2,apple

**Q6. What is the difference between .map(), .apply(), and .replace() for a Series? When would you reach
for each?**

.map() it applies a dictionary or function to every item in the series and an item in your column is not found in that dictionary,pandas will overwrite with nan

.apply() it passes each elemnt through a coustom python function or lambada expresion while it is the most flexable tool

.replace() it targets specific values and leaves everything else untouched if a value is not mached in your mapping dictionery it remains exactly as it

**Q7. What is the SettingWithCopyWarning? Give one example of code that triggers it and one way to fix
it. (Hint: the chained-assignment pattern.)**

this warning is almost always triggered by the chained-assignment pattern, which means using two sets of square brackets [][] back-to-back in a single line of code.

import pandas as pd

data={'Name': ['Alice', 'Bob', 'Charlie'], 'Status': ['Silver', 'Gold', 'Silver']}
df = pd.DataFrame(data)

silver=df(df['status']=='silver')

silver['status'][0]='vip'

this will gives an erorr
the fixed one is

silver=df[df['status']=='silver'].copy()
silver.loc[0,'status']='vip]


**Q8. Explain pd.cut() vs pd.qcut(). If you have annual income data and want to label customers as Low /
Mid / High earners, which one fits better? Why?**

pd.cut() divied the range from minum to maxium value into equal
the spaceing btw the no.of each bin is unquie

pd.qcut() divieds the data based on percentiles the spacing btw numbers can vary but count recored bin will be exactly the same
for the real world annual income data pd.cut() is fits much better
income distribution in real world is highy skweded a small percentage of extreme ultra high earns pull the maximum value way out to theright

# Section B

In [ ]:
##Q9. Predict the output. What's in df at the end?
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df2 = df
df2['a'] = [10, 20, 30]
print(df)

# the output is {'a':[10,20,30],'b':[4,5,6]}
#i think is giving like above but is mutidenmsion so the output is in table

    a  b
0  10  4
1  20  5
2  30  6

In [ ]:
# Q10. Predict both outputs.
import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, 4, 5])
print(s.mean())
print(s.sum())
#the mean is around 2.2 like and sum is 12
#for that mean is not consider the nan value so is divied by 4 so mean is 3 but me 5 so is 2.somthing

3.0
12.0

In [ ]:
# Q11. Predict the dtype and the sum.
import pandas as pd
df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())
#prices 100 200 nan 400 like the table appers and dtype is int and sum is 700
#its going to floating numbers and i take intggers

float64
700.0

In [ ]:
# Q12. Predict the type of df.loc[0].
import pandas as pd
df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})
print(df.loc[0])
print(type(df.loc[0]))
#name  age
#Rahul 22
#sting

#i dont know is an dtype of object

name    Rahul
age        22
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
# Q13. Predict – and explain what's wrong with the modification line.
import pandas as pd
df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})
df_filtered = df[df['rating'] > 4].copy()
df_filtered['rating'] = df_filtered['rating'] * 2
# what warning?
print(df)
print(df_filtered)
# df_filtered is can get an warning due to sliceing and multipication
#by adding at last of copy() function to the slice is not get the copywaring error

   rating
0     4.5
1     3.8
2     4.2
3     5.0
   rating
0     9.0
2     8.4
3    10.0

In [ ]:
# Q14. Predict the result AND its dtype. Why is the dtype what it is?
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4]})
result = df['a'].apply(lambda x: x**2 if x > 2 else 'small')
print(result)
print(result.dtype)
#a:  small small  9 16
#dtype is intgger
#using to in column thats mean is an object

0    small
1    small
2        9
3       16
Name: a, dtype: object
object

In [ ]:
# Q15. Predict each output. What's the difference between nunique(), len(unique()), and value_counts()?
import pandas as pd
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Delhi', 'Bengaluru', None]})
print(df['city'].nunique())
print(len(df['city'].unique()))
print(df['city'].value_counts())
#delhi
#3
#delhi 2,mubai 1,bengaluru 1
#the nunqiue is used to giving without nan as a count, using len(unqiue()) this is find
#the total diifernts ,the value count is used to count the no.of items in that data

3
4
city
Delhi        2
Mumbai       1
Bengaluru    1
Name: count, dtype: int64

In [ ]:
# Q16. Predict each line. The commented line will throw an error or silently break — explain why.
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})
print(df[df['a'] > 1])
#print(df[df['a'] > 1 & df['b'] > 15])
# <-- what's wrong here?
print(df[(df['a'] > 1) & (df['b'] > 15)])
# a: 2,3 b: 10,20,30
# a: 2,3 b: 10,20,30
# in that the df function is confused due to without sparting these queres

   a   b
1  2  20
2  3  30
   a   b
1  2  20
2  3  30

Section C

Q17. After loading the raw CSV (before cleaning), answer:
(a) How many rows and columns?
(b) How many missing values are in each column?
(c) How many exact duplicate rows are present?

In [ ]:
import pandas as pd
df=pd.read_csv('indian_startups_fundingDADS.csv')
print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())
df.head()

(468, 8)
Startup Name      0
City              0
INDUSTRY          0
Funding Stage     0
Amount            0
Funding Date     19
Investors        10
Founded Year     23
dtype: int64
18

,Startup Name,City,INDUSTRY,Funding Stage,Amount,Funding Date,Investors,Founded Year
0,PlayTime Games,DELHI,ecommerce,Series-E,INR 942 Crore,29/02/2024,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebel Foods,ahmedabad,BeautyTech,Pre-A,1440,18/08/2018,Lightspeed,2017.0
2,Freshworks,Kolkata,AgriTech,Pre-Series A,329 Cr,14 Jul 2020,Info Edge,2020.0
3,BigBasket,Mumbai,ecommerce,Series D,₹1405 Cr,31/03/2018,B Capital,2016.0
4,Ola,KOLKATA,EdTech,SERIES E,₹2223 Cr,24-08-2021,Falcon Edge,2017.0

Q18. After cleaning column names to snake_case, print the cleaned column names sorted
alphabetically. Don't manually type them – use Python on df.columns.

In [ ]:
df.columns=(df.columns.str.lower().str.replace(' ','_'))
print(df.columns)

Index(['startup_name_', 'city', 'industry', 'funding_stage', 'amount',
       'funding_date', 'investors', 'founded_year'],
      dtype='object')

Q19. Without using .describe(), compute these statistics on the cleaned founded_year column (after
dropping NaN): count, mean, min, max, median, std. Print as a single dictionary with these exact keys.

In [ ]:
clean_Years=df['founded_year'].dropna()
stats_dict={
    'count': int(clean_Years.count()),
    'mean': float(clean_Years.mean()),
    'min': float(clean_Years.min()),
    'max': float(clean_Years.max()),
    'median': float(clean_Years.median()),
    'std': float(clean_Years.std())}
print(stats_dict)

{'count': 445, 'mean': 2016.4606741573034, 'min': 2008.0, 'max': 2022.0, 'median': 2017.0, 'std': 4.187218270138983}

Q20. After cleaning the city column with the aliases mapped, print all unique city names sorted
alphabetically. There should be exactly 10 cities and no duplicates from case or whitespace.

In [ ]:
df['city']=df['city'].str.strip().str.title()
city_aliases={
    "Bangalore": "Bengaluru", "Blr": "Bengaluru",
    "Bombay": "Mumbai", "Bom": "Mumbai",
    "Calcutta": "Kolkata",
    "Madras": "Chennai",
    "New Delhi": "Delhi",
    "Gurgaon": "Gurugram", "Ggn": "Gurugram",
    "Hyd": "Hyderabad"

}
df['city']=df['city'].replace(city_aliases)
uniqes_citys=df['city'].unique()
print(sorted(uniqes_citys))

['Ahmedabad', 'Bengaluru', 'Chennai', 'Delhi', 'Gurugram', 'Hyderabad', 'Kolkata', 'Mumbai', 'Noida', 'Pune']

Q21. After standardising the industry column using a dict, print the count of startups per industry sorted
from most to least common (use value_counts()).

In [ ]:
df['industry']=df['industry'].str.strip().str.title()
uniqesindestryes=df['industry'].unique()
print(uniqesindestryes)
industry_aliases={
    "Ai Ml": "Ai/Ml", "Aiml": "Ai/Ml", "Ai-Ml": "Ai/Ml",
    "Agri Tech": "Agritech", "Agri-Tech": "Agritech",
    "Beauty-Tech": "Beautytech",
    "Ed-Tech": "Edtech",
    "E-Commerce": "Ecommerce",
    "Electric-Vehicles": "Electric Vehicles", "Ev": "Electric Vehicles",
    "Fin-Tech": "Fintech", "Ft": "Fintech",
    "Food Tech": "Foodtech", "Food-Tech": "Foodtech",
    "Games": "Gaming",
    "Health-Tech": "Healthtech", "Health Tech": "Healthtech",
    "Prop-Tech": "Proptech",
    "Travel-Tech": "Traveltech"

}
df['industry']=df['industry'].replace(industry_aliases)
industry_counts=df['industry'].value_counts()
print(industry_counts)

['Ecommerce' 'Beautytech' 'Agritech' 'Edtech' 'Food Tech' 'Saas'
 'Travel-Tech' 'Ai Ml' 'Health-Tech' 'Electric-Vehicles' 'Fin-Tech'
 'Electric Vehicles' 'Logistics' 'Proptech' 'Fintech' 'Prop-Tech'
 'Food-Tech' 'Aiml' 'Foodtech' 'Healthtech' 'Ai/Ml' 'Ev' 'Gaming' 'Ai-Ml'
 'Agri Tech' 'Games' 'Agri-Tech' 'E-Commerce' 'Health Tech' 'Traveltech'
 'Beauty-Tech' 'Ft' 'Ed-Tech']
industry
Ai/Ml                56
Foodtech             39
Saas                 38
Gaming               37
Beautytech           36
Proptech             34
Traveltech           34
Healthtech           33
Ecommerce            33
Agritech             30
Logistics            27
Electric Vehicles    27
Edtech               22
Fintech              22
Name: count, dtype: int64

Q22. After converting amount to numeric, print:
(a) The dtype of the column
(b) How many NaN values are there (from 'Undisclosed' entries)
(c) The mean funding amount (ignoring NaN)
(d) The minimum and maximum funding amount

In [ ]:

df['amount']=df['amount'].astype(str).str.replace('INR','').str.replace('₹','').str.replace('cr','').str.replace(' ','').str.replace('Cr','').str.replace('Crore','',regex=True).str.strip()
df['amount']=pd.to_numeric(df['amount'],errors='coerce')
print(df['amount'].dtype)
print(df['amount'].isnull().sum())
print(df['amount'].mean())
print(df['amount'].min())
print(df['amount'].max())
df.head()

float64
127
669.6539589442815
4.0
3549.0

,startup_name_,city,industry,funding_stage,amount,funding_date,investors,founded_year
0,PlayTime Games,Delhi,ecommerce,Series E,NaN,2024-02-29,"Ranjan Pai, Prosus Ventures",2020.0
1,Rebel Foods,Ahmedabad,BeautyTech,Pre-Series A,1440.0,2018-08-18,Lightspeed,2017.0
2,Freshworks,Kolkata,AgriTech,Pre-Series A,329.0,NaT,Info Edge,2020.0
3,BigBasket,Mumbai,ecommerce,Series D,1405.0,2018-03-31,B Capital,2016.0
4,Ola,Kolkata,EdTech,Series E,2223.0,NaT,Falcon Edge,2017.0

Q23. After converting funding_date to datetime:
(a) Count how many deals happened in each year. Use .dt.year.
(b) Print the year with the highest number of funding deals.

In [ ]:
import pandas as pd
df=pd.read_csv('indian_startups_fundingDADS.csv')
df.columns=(df.columns.str.lower().str.replace(' ','_'))
df['funding_date']=pd.to_datetime(df['funding_date'],errors='coerce',dayfirst=True)

year_counts=df['funding_date'].dt.year.value_counts()
print(year_counts)
max_year=year_counts.idxmax()
print(max_year)

funding_date
2022.0    24
2023.0    14
2021.0    14
2024.0     7
2019.0     7
2020.0     6
2017.0     5
2018.0     5
2016.0     4
2015.0     3
2011.0     1
2014.0     1
2013.0     1
2012.0     1
Name: count, dtype: int64
2022.0

Q24. After standardising funding_stage, print the count of startups per stage (sorted from most
common to least).

In [ ]:
df['funding_stage']=df['funding_stage'].str.strip().str.title()
uniqefindingstage=df['funding_stage'].unique()
print(uniqefindingstage)
funding_stage_aliases={
    'Pre-Seed': 'Pre-Seed', 'Preseed': 'Pre-Seed', 'Pre Seed': 'Pre-Seed',
    'Seed': 'Seed','Pre-A': 'Pre-Series A',
    'Pre-Series A': 'Pre-Series A', 'Pre Series A': 'Pre-Series A',
    'Series A': 'Series A', 'Series-A': 'Series A', 'Series_A': 'Series A',
    'Series B': 'Series B', 'Series-B': 'Series B', 'Series_B': 'Series B',
    'Series C': 'Series C', 'Series-C': 'Series C',
    'Series D': 'Series D', 'Series-D': 'Series D',
    'Series E': 'Series E', 'Series-E': 'Series E',
    'Bridge': 'Bridge',
    'Ipo': 'IPO', 'Pre-Ipo': 'Pre-IPO'

}
df['funding_stage']=df['funding_stage'].replace(funding_stage_aliases)
stages_count=df['funding_stage'].value_counts()
print(stages_count)

['Series-E' 'Pre-A' 'Pre-Series A' 'Series D' 'Series E' 'Series C' 'Ipo'
 'Series A' 'Series B' 'Pre-Seed' 'Pre-Ipo' 'Seed' 'Series_B' 'Bridge'
 'Pre Series A' 'Preseed' 'Series-D' 'Series-B' 'Series-C' 'Series-A'
 'Pre Seed' 'Series_A']
funding_stage
Series B        58
Series A        49
Seed            49
Series E        48
Pre-Seed        48
Series C        47
Bridge          42
Pre-Series A    41
Series D        40
IPO             34
Pre-IPO         12
Name: count, dtype: int64

Q25. Find all Bengaluru-based startups with funding amount > 100 Cr. Print the startup_name and
amount columns, sorted by amount descending.

In [ ]:
df['city']=df['city'].str.strip().str.title()
city_aliases={
     "Bangalore": "Bengaluru",
    "Blr": "Bengaluru"
}
df['city']=df['city'].replace(city_aliases)
bangluru=df[(df['city']=='Bengaluru' )&(df['amount']>100) ]
startups=bangluru.sort_values(by='amount',ascending=False)
print(startups[['startup_name_','amount']])

      startup_name_  amount
311        RouteMap  3528.0
226     AgriConnect  3526.0
329     WhiteHat Jr  3511.0
154        EcoMotor  2244.0
309        EcoMotor  2244.0
98          Meesho   2231.0
146       Curefoods  2230.0
26      MediConnect  2226.0
252  PlayTime Games  1410.0
369            Cred   950.0
67     Simplilearn    923.0
447        AgroPlus   726.0
291     AgriConnect   713.0
255      Harvestify   497.0
341          Practo   486.0
88            Zepto   455.0
149     MediConnect   304.0
40        RuPayPro    186.0
182         FetchIt   150.0
434       Games24x7   118.0
398         Cuemath   115.0

Q26. Using .isin(), find startups whose industry is one of: Fintech, Edtech, HealthTech. Print the total
count.

In [ ]:
finding_indst=['Fintech', 'Edtech', 'HealthTech']
filtered_indst=df[df['industry'].isin(finding_indst)]
total_count=len(filtered_indst)
print("total:",total_count)

total: 19

Q27. Using .between(), find startups founded between 2015 and 2020 (both inclusive). Print the count.
Be careful – founded_year has missing values.

In [ ]:

finding_btws=df['founded_year'].between(2015,2020)
total_count=finding_btws.count()
print(finding_btws)
print("total:",total_count)

0       True
1       True
2       True
3       True
4       True
       ...
463    False
464    False
465     True
466     True
467     True
Name: founded_year, Length: 468, dtype: bool
total: 468

Q28. Using .str.contains() with case=False and na=False, find all startups whose name contains the word
'pay'. Print the unique names.

In [ ]:
from enum import unique
payinstartups=df['startup_name_'].str.contains('pay',case=False,na=False)
unique_payinstartups=df[payinstartups]['startup_name_'].str.strip().unique()
print(unique_payinstartups)

['RuPayPro' 'Razorpay' 'Paytm' 'PayBuddy' 'QuickPay India']

Q29. Add a new column funding_efficiency = amount / (2024 - founded_year). Higher = raised more
capital per year of existence. Sort by funding_efficiency descending. Print top 10 with name, industry,
amount, founded_year, and funding_efficiency.

In [ ]:
df['funding_efficiency']=df['amount']/((2024-df['founded_year']))
df=df.sort_values(by='funding_efficiency',ascending=False)
efficeny_fund=(df[['startup_name_','industry','amount','founded_year','funding_efficiency']])
print(efficeny_fund.head(10))

    startup_name_           industry  amount  founded_year  funding_efficiency
322    ClassroomX              AI/ML  3520.0        2022.0         1760.000000
123         Nykaa          logistics  3515.0        2021.0         1171.666667
309      EcoMotor             gaming  2244.0        2022.0         1122.000000
154      EcoMotor             gaming  2244.0        2022.0         1122.000000
158    MakeMyTrip  Electric Vehicles  2202.0        2022.0         1101.000000
55        Blinkit  Electric Vehicles  2196.0        2022.0         1098.000000
246   FitnessPlus            FinTech  3545.0        2020.0          886.250000
202      PropMart         TRAVELTECH  2201.0        2021.0          733.666667
8       GroomGuru              AI ML  2195.0        2021.0          731.666667
167   FitnessPlus              AI/ML  1430.0        2022.0          715.000000

Q30. Using .apply() with a lambda, add a funding_tier column based on amount:
amount ≥ 1000 Cr → 'Unicorn'
amount ≥ 500 Cr → 'Mega'
amount ≥ 100 Cr → 'Large'
amount ≥ 10 Cr → 'Mid'
else (including NaN) → 'Small / Unknown'
Print the count of startups in each tier.

In [ ]:
df['funding_tier']=df['amount'].apply(lambda x: 'Unicorn' if x>=1000 else ('Mega' if x>=500 else ('Large' if x>=100 else ('Mid' if x>=10 else 'Small/Unknown'))))
print(df['funding_tier'].value_counts())

funding_tier
Small/Unknown    136
Large            108
Mid              102
Unicorn           65
Mega              57
Name: count, dtype: int64

Q31. Using pd.cut(), bin founded_year into 3 eras:
Before 2010 → 'Early'
2010 to 2017 → 'Growth'2018 and later → 'Recent'
Print the count of startups in each era.

In [ ]:
min_year = df['founded_year'].min() - 1
x_year = df['founded_year'].max() + 1
bins=[min_year,2009,2017,max_year]
labels=['Early','Growth','Recent']
df['era']=pd.cut(df['founded_year'],bins=bins,labels=labels)
print(df['era'].value_counts())

era
Recent    214
Growth    206
Early      25
Name: count, dtype: int64

Q32. The investors column has multiple investors separated by ', ' (comma + space). Create a new
column investor_count showing the number of investors per startup. Use .apply() with a lambda. Handle
NaN values (count = 0). Print the value_counts() of investor_count.

In [ ]:
df['investor_count']=df['investors'].apply(
    lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)
print(df['investor_count'].value_counts())

investor_count
2    208
3    122
1     98
4     30
0     10
Name: count, dtype: int64

Q33. Compute the average funding amount per industry (ignoring NaN). Sort descending. Print the top 5
industries by average funding.

In [ ]:
avg_funding=df.groupby('industry')['amount']
avg_funding=avg_funding.mean().sort_values(ascending=False)
print(avg_funding.head(5))

industry
FinTech              3545.000000
Fintech              1890.666667
Fin-Tech             1806.000000
Gaming               1449.250000
Electric Vehicles    1424.250000
Name: amount, dtype: float64

Q34. For each city, compute three metrics in a single groupby using .agg() with a dictionary:
(a) Number of startups
(b) Total funding raised (sum of amount)
(c) Average funding per startup
Print the top 10 cities by number of startups.

In [ ]:
city_metrics=df.groupby('city').agg({'startup_name_':'count','amount':['sum','mean']})
city_metrics.columns=['num_startups','total_funding','avg_funding']
top_10_cities=city_metrics.sort_values(by='num_startups',ascending=False)
print(top_10_cities.head(10))

           num_startups  total_funding  avg_funding
city
Noida                69        23815.0   496.145833
Bengaluru            51        29286.0   861.352941
Ahmedabad            45        27107.0   713.342105
Pune                 44        25608.0   800.250000
Hyderabad            33        19858.0   863.391304
Kolkata              32        18638.0   716.846154
Mumbai               29        12444.0   592.571429
Chennai              28         6472.0   269.666667
Delhi                22        21009.0  1313.062500
Gurugram             19        13323.0   783.705882

Q35. Interview-style. Which industry has the highest average funding, but only considering industries
with at least 15 startups? (Sparse industries bias the mean.) Print industry name, count, and average
funding.

In [ ]:
industry_metrics=df.groupby('industry').agg(
     startup_count=('startup_name_', 'count'),
        avg_funding=('amount', 'mean'))
filteed_indsteries=industry_metrics[industry_metrics['startup_count']>=15]
if not filteed_indsteries.empty:
    top_industry=filteed_indsteries.loc[filteed_indsteries['avg_funding'].idxmax()]
    print("industry",top_industry.name)
    print("count",top_industry['startup_count'])
    print("avg_funding",top_industry['avg_funding'])

industry TRAVELTECH
count 16.0
avg_funding 1163.2666666666667

Q36. Using pd.crosstab(), show the distribution of funding_tier across the top 5 industries by count.
Rows = industry, columns = funding_tier, values = count of startups.

In [ ]:
top_5_industries=df['industry'].value_counts().head(5).index
filtered_df=df[df['industry'].isin(top_5_industries)]
funding_distribution=pd.crosstab(
    index=filtered_df['industry'],columns=filtered_df['funding_tier'])
print(funding_distribution.loc[top_5_industries])

funding_tier  Large  Mega  Mid  Small/Unknown  Unicorn
industry
AI/ML             4     3    7              4        4
TRAVELTECH        3     5    2              1        5
BEAUTYTECH        4     0    5              5        1
logistics         3     2    3              5        1
PROPTECH          6     4    1              2        1

Q37. For each industry, find the startup with the highest funding amount. Print startup_name, industry,
city, and amount. Hint: groupby + idxmax() on amount.

In [ ]:
df_clean=df.dropna(subset=['amount'])
top_startup=df_clean.groupby('industry')['amount'].idxmax()
result=df_clean.loc[
    top_startup,['startup_name_','industry','city','amount']]
print(result)

           startup_name_           industry       city  amount
83               Vedantu           AGRITECH       Pune   445.0
8              GroomGuru              AI ML  Hyderabad  2195.0
406               GlowUp              AI-ML     Mumbai  1441.0
322           ClassroomX              AI/ML  Ahmedabad  3520.0
197              Postman               AIML       Pune  2205.0
262               InMobi          Agri Tech  Ahmedabad   699.0
62              CashFlow          Agri-Tech  Ahmedabad   497.0
2             Freshworks           AgriTech    Kolkata   329.0
98               Meesho          BEAUTYTECH  Bengaluru  2231.0
414       PlayTime Games        Beauty-Tech        Hyd   133.0
93             VitalCare         BeautyTech       Pune  3522.0
439           CreditMate         E-Commerce       Pune  2234.0
395             EcoMotor         E-commerce      Noida   718.0
305              FetchIt          ECOMMERCE  Hyderabad   684.0
384                  1mg             EDTECH   Gurugram   728.0
316            InstaLoan                 EV    Chennai   923.0
135  FastTrack Logistics          Ecommerce  Hyderabad  1427.0
432            BoldFoods            Ed-Tech       Pune   168.0
4                    Ola             EdTech    Kolkata  2223.0
175             PropMart             Edtech      Delhi  3534.0
311             RouteMap  Electric Vehicles  Bengaluru  3528.0
12                   Ola  Electric-Vehicles      Delhi  3520.0
446          HealthLink             FINTECH     Bombay   475.0
279            GreenGrow          FOOD-TECH    Gurgaon   900.0
433       PlayTime Games                 FT  Hyderabad   950.0
15              BillBoss           Fin-Tech      Noida  2202.0
246          FitnessPlus            FinTech      Delhi  3545.0
106           CleanSlate            Fintech  Ahmedabad  3525.0
317              Vedantu          Food Tech    Chennai   726.0
110               Studyo          Food-Tech   Gurugram  3545.0
452        BookMyService           FoodTech      Noida  1444.0
271                Nykaa             GAMING     Mumbai  2244.0
382            AgriBoost              Games    Kolkata  3507.0
179            WealthWiz             Gaming    Kolkata  3549.0
193           TripScribe         HEALTHTECH      Delhi   933.0
130            DermaPlus        Health Tech    Gurgaon   711.0
58                   MPL        Health-Tech     Mumbai   677.0
373           TripScribe         HealthTech       Pune  1421.0
460             Razorpay          LOGISTICS    Kolkata   719.0
356            Mamaearth          Logistics       Pune  2214.0
456             DigiKart           PROPTECH    Gurgaon  1430.0
447             AgroPlus          Prop-Tech  Bengaluru   726.0
157              Watchio           PropTech        Ggn   213.0
94                  Cred               SAAS  Hyderabad  2214.0
64              FarmTech               SaaS    Kolkata  2231.0
56           WhiteHat Jr               Saas  Hyderabad  2250.0
205            DocOnTime         TRAVELTECH     Mumbai  3529.0
28              RuPayPro        Travel-Tech  Ahmedabad  3541.0
199            FinSphere         TravelTech    Chennai   927.0
81            CreditMate           agritech        Hyd    50.0
312        BookMyService          ecommerce  Hyderabad  1411.0
329          WhiteHat Jr                 ev  Bengaluru  3511.0
67          Simplilearn             fintech  Bengaluru   923.0
214               upGrad           foodtech    Gurgaon  3517.0
309             EcoMotor             gaming  Bengaluru  2244.0
386           InvestEdge         healthtech    Kolkata  2219.0
123                Nykaa          logistics      Delhi  3515.0
240            Games24x7               saas   Gurugram  1398.0

Q38. Emerging player finder. An 'emerging player' is a startup founded in 2019 or later, with funding ≥
100 Cr, in one of Fintech / Edtech / HealthTech. Find all of them, sort by amount descending, print
name, industry, city, founded_year, and amount. Why might a VC analyst care about this list?

In [ ]:
target_industries = ['Fintech', 'Edtech', 'HealthTech']
filtered_df = df[(df['founded_year'] >=2019)&(df['amount']>=100)&(df['industry'].isin(target_industries))]
sorted_df=filtered_df.sort_values(by='amount',ascending=False)
print(sorted_df[['startup_name_','industry','city','founded_year','amount']])

    startup_name_ industry      city  founded_year  amount
178    ClassroomX  Fintech     Noida        2022.0  1418.0
342       VoltCar   Edtech       Hyd        2021.0   916.0
417   VillageMart   Edtech  Gurugram        2021.0   896.0
370     AgriBoost  Fintech     Delhi        2021.0   729.0

Q39. Investor hub analysis. A foreign investor wants to know which Indian city has the highest TOTAL
funding raised, considering only cities with at least 20 startups (so the number is meaningful). Print city
name, count, and total funding.

In [ ]:
city_metrices=(df.dropna(subset=['city' ,'amount']).groupby('city').agg(
    startup_count=('startup_name_','count'),
    total_funding=('amount','sum')).reset_index())
filtered_cities=city_metrices[city_metrices['startup_count']>=20]
if not filtered_cities.empty:
    top_city=filtered_cities.loc[filtered_cities['total_funding'].idxmax()]
    print("city",top_city['city'])
    print("count",top_city['startup_count'])
    print("total_funding",top_city['total_funding'])

city Bengaluru
count 34
total_funding 29286.0

Q40. Market saturation. For each combination of (city, industry), count the number of startups. Print the
top 10 most-saturated combinations. This tells a new founder where competition is most intense – and
by elimination, where the gaps might be

In [ ]:
df_clea=df.dropna(subset=['city','industry'])
city_industry_counts=(
    df_clea.groupby(['city','industry'])
    .agg(startup_count=('startup_name_','count'))
    .reset_index())
top_10_saturated=city_industry_counts.sort_values(by='startup_count',ascending=False).head(10)
print(top_10_saturated)

          city    industry  startup_count
281      Noida  BEAUTYTECH              8
292      Noida    FoodTech              5
305      Noida  TRAVELTECH              4
57   Bengaluru      gaming              4
315       Pune       AI/ML              4
5    Ahmedabad   Agri Tech              3
334       Pune    PROPTECH              3
311      Noida   logistics              3
263     Mumbai  TRAVELTECH              3
203  Hyderabad   Prop-Tech              3